name: quick_navbar
description: "A new Flutter package project."
version: 0.0.1
repository: https://github.com/Calebh101/quick_navbar_flutter

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0