name: quick_navbar
description: "quick_navbar is a package to allow you to create quick and stylish bottom navigation bars for your flutter apps."
version: 0.0.5
repository: https://github.com/Calebh101/quick_navbar_flutter

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0

linter:
  rules:
    - public_member_api_docs