name: quick_navbar
description: "quick_navbar is a quick, easy-to-use package to allow you to create simple but stylish bottom (or side) navigation bars."
version: 1.2.0
repository: https://github.com/Calebh101/quick_navbar_flutter

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0

linter:
  rules:
    - public_member_api_docs